### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by MattSom** [jyhwng/dashboard#2]
Hi, can you add any instructions how to install and try out locally?

Cheers!

**Comment by kgrvamsi** [comment]
@MattSom give a try like below
1. clone the repo
2. yarn install or npm install
3. yarn start or npm start would bring the UI up

**Comment by jyhwng** [comment]
Hi @MattSom, and thank you @kgrvamsi!

It's embarrassing not having a README.md file yet and this is a good reminder :) Will create one soon!
